defmodule FeatherAdapters.SpamFilters.Pipeline do
  @moduledoc false

  # Glue between `FeatherAdapters.SpamFilters` (the behaviour) and
  # `FeatherAdapters.Adapter` (the lifecycle). Not part of the public API —
  # call sites are generated by `use FeatherAdapters.SpamFilters`.

  alias FeatherAdapters.SpamFilters.Action

  @type state :: %{
          filter: any(),
          opts: keyword(),
          module: module()
        }

  @doc false
  @spec init(module(), keyword()) :: state()
  def init(module, opts) do
    filter_state =
      if function_exported?(module, :init_filter, 1) do
        module.init_filter(opts)
      else
        %{}
      end

    %{filter: filter_state, opts: opts, module: module}
  end

  @doc false
  def run(module, classify_fn, adapter_phase, arg, meta, %{filter: fs} = state) do
    case apply(module, classify_fn, [arg, meta, fs]) do
      {verdict, new_fs} ->
        new_state = %{state | filter: new_fs}
        log_verdict(module, adapter_phase, verdict, meta)

        case Action.apply_verdict(verdict, meta, module, state.opts) do
          {:cont, new_meta} ->
            log_action(module, verdict, new_meta, :cont)
            {:ok, new_meta, new_state}

          {:halt, reason} ->
            log_action(module, verdict, meta, {:halt, reason})
            {:halt, reason, new_state}
        end

      other ->
        raise ArgumentError,
              "#{inspect(module)}.#{classify_fn}/3 returned #{inspect(other)}; " <>
                "expected {verdict, state}"
    end
  end

  # ---- automatic logging via Feather.Logger -------------------------------
  # Every verdict + action is emitted at an appropriate level. The
  # session's Feather.Logger configuration decides where it lands
  # (console / file / syslog). Operators don't need to wire a separate
  # logging adapter to see what spam filters are doing.

  defp log_verdict(module, phase, verdict, meta) do
    scanner = short_name(module)
    ctx = context_fields(meta)

    case verdict do
      :ham ->
        Feather.Logger.debug("[spam] scanner=#{scanner} phase=#{phase} verdict=ham#{ctx}")

      {:ham, score, tags} ->
        Feather.Logger.info(
          "[spam] scanner=#{scanner} phase=#{phase} verdict=ham score=#{score}" <>
            tags_field(tags) <> ctx
        )

      {:spam, score, tags} ->
        Feather.Logger.warning(
          "[spam] scanner=#{scanner} phase=#{phase} verdict=spam score=#{score}" <>
            tags_field(tags) <> ctx
        )

      :defer ->
        Feather.Logger.warning(
          "[spam] scanner=#{scanner} phase=#{phase} verdict=defer (scanner unavailable)" <> ctx
        )

      :skip ->
        Feather.Logger.debug("[spam] scanner=#{scanner} phase=#{phase} verdict=skip#{ctx}")
    end
  end

  defp log_action(module, _verdict, meta, :cont) do
    cond do
      meta[:quarantine] == true ->
        Feather.Logger.warning(
          "[spam] scanner=#{short_name(module)} action=quarantine" <> context_fields(meta)
        )

      is_list(meta[:spam_headers]) and meta[:spam_headers] != [] ->
        Feather.Logger.info(
          "[spam] scanner=#{short_name(module)} action=tag headers=#{length(meta[:spam_headers])}" <>
            context_fields(meta)
        )

      true ->
        :ok
    end
  end

  defp log_action(module, _verdict, meta, {:halt, reason}) do
    Feather.Logger.warning(
      "[spam] scanner=#{short_name(module)} action=halt reason=#{inspect(reason)}" <>
        context_fields(meta)
    )
  end

  defp tags_field([]), do: ""
  defp tags_field(tags), do: " tags=" <> Enum.map_join(tags, ",", &to_string/1)

  defp context_fields(meta) do
    ""
    |> maybe_append(meta[:from], &" from=#{&1}")
    |> maybe_append(meta[:ip] && format_ip(meta[:ip]), &" ip=#{&1}")
  end

  defp maybe_append(acc, nil, _f), do: acc
  defp maybe_append(acc, "", _f), do: acc
  defp maybe_append(acc, v, f), do: acc <> f.(v)

  defp short_name(module), do: module |> Module.split() |> List.last()

  defp format_ip({a, b, c, d}), do: "#{a}.#{b}.#{c}.#{d}"
  defp format_ip(ip) when is_tuple(ip), do: ip |> :inet.ntoa() |> to_string()
  defp format_ip(ip) when is_binary(ip), do: ip
  defp format_ip(_), do: nil
end
